// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxexhqcslnfhgndygnow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4ZXhocWNzbG5maGduZHlnbm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDA2ODYsImV4cCI6MjA2MzY3NjY4Nn0.UMJEqpYJ2qhb-9nCp1nty1bmrPkdpvtm_gLNbzjOHmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);